---
name: Simo-Constrain
version: 0.01_01
author:
  - 'Yuki <kimoto.yuki@gmail.com>'
abstract: Constrain methods for Simo;
license: perl
resources:
  license: ~
requires:
  Scalar::Util: 0
build_requires:
  Test::More: 0
provides:
  Simo::Constrain:
    file: lib/Simo/Constrain.pm
    version: 0.01_01
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
