---
name: Simo
version: 0.1008
author:
  - 'Yuki <kimoto.yuki@gmail.com>'
abstract: Very simple framework for Object Oriented Perl.
license: perl
resources:
  license: ~
requires:
  Storable: 0
build_requires:
  Simo::Error: 0.0206
  Test::More: 0
provides:
  DB:
    file: lib/Simo.pm
  Simo:
    file: lib/Simo.pm
    version: 0.1008
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
